### PR TITLE
I added a folder called 'R Programming Language Explained'

### PR DESCRIPTION
**Pull request by CarlosViniMSouza**
What did I do :

1 - Divide the article between topics;
2 - Each topic was transcribed in the R language;
3 - There are 2 markdown files: 'presentation' and 'more information' (all with original links from the article page)
4 - the article link is in the README.md of the Project

* I hope my contribution can help you and everyone in the R community

### CODE REVIEW

**Comment by dmpe** [comment]
> R_Programming_Language_Explained/Objects_in_R.R

Remove it please if it is empty

**Comment by CarlosViniMSouza** [comment]
added the contents of the 'Object_inR.R' file that should be in the first commit

**Comment by CarlosViniMSouza** [comment]
dmpe, is there a problem with that last request?

**Comment by CarlosViniMSouza** [comment]
Thanks you for accepting me as a contributor to this project 🖖🤓

**Pull request merged**
